approach:
- original
dataset_size: 20
dialogue_generation_model:
  model_apikey: ''
  model_endpoint: http://localhost:5000/
  model_name: llama-3-8b-instruct
  model_type: openllm
dialogue_size: 5
kghost: 206.12.95.86
kgname: mag
kgport: 8894
logging: true
outputdir: ./results/mag/original/multi-llm-1
pipeline_type: original
prompt: 1
question_generation_model:
  model_apikey: ''
  model_endpoint: http://localhost:5000/
  model_name: llama-3-8b-instruct
  model_type: openllm
redishost: localhost
sparql_generation_model:
  model_apikey: ''
  model_endpoint: http://localhost:5000/
  model_name: codellama-13b
  model_type: openllm
temperature: 0.5
tracing: true
use_label: true
wandb_project: chatty-gen-benchmark
