approach:
- subgraph-summarized
comman_model:
  model_apikey: ''
  model_endpoint: ''
  model_name: gpt-3.5
  model_type: openai
dataset_size: 20
dialogue_size: 5
kghost: 206.12.95.86
kgname: dbpedia
kgport: 8894
logging: true
outputdir: ./results/dbpedia/subgraph-summarized/gpt-3.5
pipeline_type: original
prompt: 1
redishost: localhost
temperature: 0.5
tracing: true
use_label: true
wandb_project: chatty-gen-benchmark
